const CITIES={varna:{name:'Варна',lat:43.2141,lon:27.9147,tz:'Europe/Sofia'},odessa:{name:'Одесса',lat:46.4825,lon:30.7233,tz:'Europe/Kyiv'}};
let cityKey='varna';const $=id=>document.getElementById(id);
const weatherCode={0:['☀','Ясно'],1:['🌤','Преимущественно ясно'],2:['⛅','Переменная облачность'],3:['☁','Пасмурно'],45:['🌫','Туман'],48:['🌫','Изморозь'],51:['🌦','Морось'],53:['🌦','Морось'],55:['🌧','Сильная морось'],61:['🌧','Небольшой дождь'],63:['🌧','Дождь'],65:['🌧','Сильный дождь'],71:['🌨','Снег'],73:['❄','Снег'],75:['❄','Сильный снег'],80:['🌦','Ливни'],81:['🌧','Ливни'],82:['🌧','Сильные ливни'],95:['⛈','Гроза'],96:['⛈','Гроза с градом'],99:['⛈','Гроза с градом']};
const INFO={
 weather:['Погода','Текущие условия и прогноз для выбранного города. Данные обновляются автоматически.'],temperature:['Температура','Температура воздуха на высоте около 2 метров над землёй.'],condition:['Состояние неба','Описание текущего состояния атмосферы по международному коду WMO. Значок показывает солнце, облачность, дождь, снег или грозу.'],feels:['Ощущается','Расчётная ощущаемая температура. Она учитывает температуру, ветер и влажность.'],humidity:['Влажность','Относительная влажность воздуха. Высокие значения означают больше водяного пара в воздухе.'],wind:['Ветер','Скорость ветра на высоте 10 метров над поверхностью.'],pressure:['Атмосферное давление','Давление, приведённое к уровню моря. Измеряется в гПа.'],visibility:['Видимость','Расчётная горизонтальная видимость. Снижение часто связано с туманом, осадками или аэрозолями.'],uv:['UV индекс','Индекс ультрафиолетового излучения. Чем выше значение, тем сильнее защита нужна при нахождении на солнце.'],kp:['Kp индекс','Планетарный Kp показывает возмущение магнитного поля Земли. 0–2 обычно спокойно, 3–4 возмущённо, 5 и выше соответствует геомагнитной буре.'],kpmax:['Максимальный Kp за 24 часа','Наибольшее значение Kp среди доступных наблюдений за последние 24 часа.'],kpforecast:['Прогноз Kp','Максимальное прогнозируемое значение Kp на ближайшие 24 часа. NOAA использует шкалу G1–G5 для геомагнитных бурь.'],aqi:['Качество воздуха','EU AQI — европейский индекс качества воздуха. Чем ниже значение, тем лучше качество воздуха.'],pm25:['PM2.5','Мелкие частицы диаметром до 2,5 микрометра. Они могут глубоко проникать в дыхательные пути.'],pm10:['PM10','Взвешенные частицы диаметром до 10 микрометров. Источниками бывают пыль, дорожное движение и другие аэрозоли.'],o3:['Озон O₃','Приземный озон является загрязнителем воздуха. Высокие концентрации чаще возникают при сильном солнечном излучении.'],moon:['Фаза Луны','Текущая фаза, освещённость, время восхода и захода Луны для выбранного города.'],solar:['Солнечная активность','Показатели активности Солнца и солнечного ветра. Они используются для оценки космической погоды.'],xray:['Рентгеновское излучение Солнца','Поток солнечного рентгеновского излучения по данным спутников GOES. Сильные всплески могут сопровождать солнечные вспышки.'],solarwind:['Солнечный ветер','Скорость потока заряженных частиц от Солнца. Повышение скорости может сопровождать возмущённую космическую погоду.'],quake:['Землетрясения','Показываются землетрясения магнитудой от 1.5 в радиусе до 500 км от выбранного города за последние 30 дней.'],hourly:['Почасовой прогноз','На каждый час показываются температура, состояние неба и вероятность осадков. Если вероятность осадков высокая, это отмечается отдельно.']};
function openInfo(key,value=''){const x=INFO[key]||['Информация','Данные ATLAS'];$('modalKicker').textContent='ATLAS · INFO';$('modalTitle').textContent=x[0];$('modalText').textContent=x[1];$('modalValue').textContent=value||'';$('modalBackdrop').classList.add('open')}
document.querySelectorAll('[data-info]').forEach(el=>el.addEventListener('click',e=>{e.stopPropagation();const key=el.dataset.info;let value='';const target=el.id?el:el.querySelector('strong');if(target)value=target.textContent.trim();openInfo(key,value)}));
$('modalClose').onclick=()=>$('modalBackdrop').classList.remove('open');$('modalBackdrop').onclick=e=>{if(e.target===$('modalBackdrop'))$('modalBackdrop').classList.remove('open')};document.addEventListener('keydown',e=>{if(e.key==='Escape')$('modalBackdrop').classList.remove('open')});
async function json(url){const r=await fetch(url+(url.includes('?')?'&':'?')+'_='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()}
function localDate(s){return new Date(s.replace(' ','T'))}
function fmtTime(s){return new Intl.DateTimeFormat('ru-RU',{hour:'2-digit',minute:'2-digit'}).format(new Date(s))}
function moonPhaseName(p){if(p<.03||p>.97)return ['Новолуние','🌑'];if(p<.22)return ['Растущая Луна','🌒'];if(p<.28)return ['Первая четверть','🌓'];if(p<.47)return ['Растущая Луна','🌔'];if(p<.53)return ['Полнолуние','🌕'];if(p<.72)return ['Убывающая Луна','🌖'];if(p<.78)return ['Последняя четверть','🌗'];return ['Убывающая Луна','🌘']}
function setWeatherIcon(code){const w=weatherCode[code]||['•','—'];$('weatherIcon').textContent=w[0];$('weatherDesc').textContent=w[1];return w[1]}
async function loadWeather(c){
 const url=`https://api.open-meteo.com/v1/forecast?latitude=${c.lat}&longitude=${c.lon}&current=temperature_2m,relative_humidity_2m,apparent_temperature,pressure_msl,wind_speed_10m,visibility,weather_code,is_day&hourly=temperature_2m,precipitation_probability,precipitation,rain,snowfall,weather_code,is_day&daily=weather_code,temperature_2m_max,temperature_2m_min,uv_index_max,sunrise,sunset,moonrise,moonset,moon_phase,precipitation_probability_max,rain_sum,snowfall_sum&forecast_days=7&timezone=${encodeURIComponent(c.tz)}`;
 const d=await json(url);const cur=d.current;const desc=setWeatherIcon(cur.weather_code);$('cityName').textContent=c.name;$('temp').textContent=Math.round(cur.temperature_2m)+'°';$('feels').textContent=Math.round(cur.apparent_temperature)+'°';$('humidity').textContent=cur.relative_humidity_2m+'%';$('wind').textContent=Math.round(cur.wind_speed_10m)+' км/ч';$('pressure').textContent=Math.round(cur.pressure_msl)+' гПа';$('visibility').textContent=(cur.visibility/1000).toFixed(1)+' км';$('uv').textContent=d.daily.uv_index_max?.[0]??'—';
 $('weatherLabel').textContent=desc;
 let days='';for(let i=0;i<7;i++){const w=weatherCode[d.daily.weather_code[i]]||['•','—'];days+=`<button class="forecast-item" data-day="${i}" data-info="hourly"><small>${new Intl.DateTimeFormat('ru-RU',{weekday:'short'}).format(new Date(d.daily.time[i]+'T12:00'))}</small><b>${w[0]}</b><strong>${Math.round(d.daily.temperature_2m_max[i])}° / ${Math.round(d.daily.temperature_2m_min[i])}°</strong><small>${d.daily.precipitation_probability_max?.[i]??0}% осадков</small></button>`}$('forecast').innerHTML=days;
 document.querySelectorAll('[data-day]').forEach(b=>b.addEventListener('click',()=>showDay(d,Number(b.dataset.day))));
 const nowIndex=Math.max(0,d.hourly.time.findIndex(t=>new Date(t).getTime()>=Date.now()));let html='';for(let i=nowIndex;i<Math.min(nowIndex+24,d.hourly.time.length);i++){const w=weatherCode[d.hourly.weather_code[i]]||['•','—'];const pp=d.hourly.precipitation_probability[i]??0;html+=`<button class="hour" data-info="hourly"><small>${fmtTime(d.hourly.time[i])}</small><b>${w[0]} ${Math.round(d.hourly.temperature_2m[i])}°</b><span class="precip">${pp>0?`💧 ${pp}%`: 'осадков нет'}</span></button>`}$('hourly').innerHTML=html;
 const p=d.daily.moon_phase?.[0];if(Number.isFinite(p)){const m=moonPhaseName(p);$('moonVisual').textContent=m[1];$('moonName').textContent=m[0];$('moonIllumination').textContent=Math.round((0.5*(1-Math.cos(2*Math.PI*p)))*100)+'%';$('moonrise').textContent=d.daily.moonrise?.[0]?fmtTime(d.daily.moonrise[0]):'—';$('moonset').textContent=d.daily.moonset?.[0]?fmtTime(d.daily.moonset[0]):'—'}
}
function showDay(d,i){const date=d.daily.time[i];let html='';for(let j=0;j<d.hourly.time.length;j++){if(d.hourly.time[j].startsWith(date)){const w=weatherCode[d.hourly.weather_code[j]]||['•','—'];const pp=d.hourly.precipitation_probability[j]??0;html+=`<button class="hour" data-info="hourly"><small>${fmtTime(d.hourly.time[j])}</small><b>${w[0]} ${Math.round(d.hourly.temperature_2m[j])}°</b><span class="precip">${pp>0?`💧 ${pp}%`: 'осадков нет'}</span></button>`}}$('hourly').innerHTML=html;openInfo('hourly',new Intl.DateTimeFormat('ru-RU',{weekday:'long',day:'numeric',month:'long'}).format(new Date(date+'T12:00'))+' · '+Math.round(d.daily.temperature_2m_min[i])+'° … '+Math.round(d.daily.temperature_2m_max[i])+'° · вероятность осадков до '+(d.daily.precipitation_probability_max?.[i]??0)+'%')}
async function loadAir(c){const d=await json(`https://air-quality-api.open-meteo.com/v1/air-quality?latitude=${c.lat}&longitude=${c.lon}&current=european_aqi,pm2_5,pm10,ozone&timezone=${encodeURIComponent(c.tz)}`);const a=d.current||{};const v=Math.round(a.european_aqi??0);$('aqi').textContent=v;$('aqiLabel').textContent=v<=20?'Очень хорошо':v<=40?'Хорошо':v<=60?'Умеренно':v<=80?'Неблагоприятно':v<=100?'Очень неблагоприятно':'Опасно';$('pm25').textContent=Math.round(a.pm2_5??0);$('pm10').textContent=Math.round(a.pm10??0);$('o3').textContent=Math.round(a.ozone??0)}
function normKp(d){if(!Array.isArray(d))return[];return d.map(x=>Array.isArray(x)?{time:x[0],kp:Number(x[1]),scale:null}:{time:x.time_tag,kp:Number(x.Kp??x.kp),scale:x.noaa_scale||null}).filter(x=>x.time&&Number.isFinite(x.kp))}
async function loadGeomag(){const [a,b]=await Promise.all([json('https://services.swpc.noaa.gov/products/noaa-planetary-k-index.json'),json('https://services.swpc.noaa.gov/products/noaa-planetary-k-index-forecast.json')]);const h=normKp(a),f=normKp(b),now=Date.now();const cur=h.at(-1)||f.find(x=>new Date(x.time).getTime()>=now);if(!cur)throw Error('Kp unavailable');const last=h.filter(x=>now-new Date(x.time).getTime()<=86400000);const max=Math.max(cur.kp,...last.map(x=>x.kp));const fut=f.filter(x=>new Date(x.time).getTime()>now&&new Date(x.time).getTime()<now+86400000);const fmax=fut.length?Math.max(...fut.map(x=>x.kp)):null;let label=cur.kp<4?'Спокойно':cur.kp<5?'Неспокойно':cur.kp<6?'Слабая магнитная буря':cur.kp<7?'Умеренная магнитная буря':cur.kp<8?'Сильная магнитная буря':'Экстремальная буря';const scale=cur.kp>=5?`G${Math.min(5,Math.floor(cur.kp-4))}`:'';$('kp').textContent=cur.kp.toFixed(1);$('kpLabel').textContent=scale?`${scale} · ${label}`:label;$('kpMax').textContent=max.toFixed(1);$('kpForecast').textContent=fmax!==null?`${fmax.toFixed(1)} · ${fmax>=5?'буря':'без бури'}`:'—';$('kpFill').style.width=Math.min(100,cur.kp/9*100)+'%';const color=cur.kp>=5?'var(--red)':cur.kp>=4?'var(--yellow)':'var(--green)';$('geomagOrb').style.background=color;$('geomagOrb').style.boxShadow=`0 0 20px ${color}`;$('stormStatus').textContent=cur.kp>=5?`Магнитная буря: ${scale||'G1'}`:fmax>=5?`Буря прогнозируется: Kp ${fmax.toFixed(1)}`:'Магнитных бурь сейчас нет'}
async function loadSolar(){try{const d=await json('https://services.swpc.noaa.gov/products/summary/solar-wind-speed.json');const x=Array.isArray(d)?d.at(-1):d;const v=Number(x?.proton_speed??x?.speed);$('solarWind').textContent=Number.isFinite(v)?Math.round(v)+' km/s':'—'}catch{$('solarWind').textContent='—'}try{const d=await json('https://services.swpc.noaa.gov/json/goes/primary/xrays-1-day.json');const x=d.at(-1);const v=Number(x?.flux);$('xray').textContent=Number.isFinite(v)?v.toExponential(1):'—'}catch{$('xray').textContent='—'}}
async function loadQuakes(c){const start=new Date(Date.now()-30*86400000).toISOString();const url=`https://earthquake.usgs.gov/fdsnws/event/1/query?format=geojson&starttime=${start}&latitude=${c.lat}&longitude=${c.lon}&maxradiuskm=500&minmagnitude=1.5&orderby=time&limit=10`;const d=await json(url);const list=d.features||[];if(!list.length){$('quakes').innerHTML='<div class="muted" style="padding:20px 0">За последние 30 дней в радиусе 500 км значимых событий не зарегистрировано.</div>';return} $('quakes').innerHTML=list.map(q=>{const p=q.properties,co=q.geometry.coordinates,dist=distanceKm(c.lat,c.lon,co[1],co[0]);return `<button class="quake" data-info="quake"><div class="mag">M ${Number(p.mag).toFixed(1)}</div><div><div class="quake-place">${p.place||'Неизвестно'}</div><div class="quake-time">${new Date(p.time).toLocaleString('ru-RU')}</div></div><div class="quake-dist">${Math.round(dist)} км</div></button>`}).join('')}
function distanceKm(a,b,c,d){const R=6371,r=x=>x*Math.PI/180,x=r(c-a),y=r(d-b),h=Math.sin(x/2)**2+Math.cos(r(a))*Math.cos(r(c))*Math.sin(y/2)**2;return 2*R*Math.asin(Math.sqrt(h))}
async function refresh(){const c=CITIES[cityKey];$('updated').textContent='обновление…';const rs=await Promise.allSettled([loadWeather(c),loadAir(c),loadGeomag(),loadSolar(),loadQuakes(c)]);const bad=rs.filter(x=>x.status==='rejected');if(bad.length)console.warn('ATLAS errors',bad.map(x=>x.reason));const n=new Date();$('updated').textContent='обновлено '+n.toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'});$('footerTime').textContent=n.toLocaleDateString('ru-RU',{day:'2-digit',month:'long',year:'numeric'})}
document.querySelectorAll('.location').forEach(b=>b.onclick=()=>{document.querySelectorAll('.location').forEach(x=>x.classList.remove('active'));b.classList.add('active');cityKey=b.dataset.city;refresh()});refresh();setInterval(refresh,600000);
